# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8955ad8605a6ccd58f310b803beb381074ee90ff749ba8f754d8736d8c10ba40080a1c73f3590b7e635d151724f1289279346bd186d288051ccd88dedfc3df13

test:
  secret_key_base: 9b3ba0122191de8f51f2ff125252daa7ad3049a289165242ca679beacf0ee884dfe9cfa61710c70a85e22bd3da9453ed50f3e732f31596e179c1a7be43563d53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
