default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: test-ruby-rails_development
  username: postgres
  password: postgres

test:
  <<: *default
  database: test-ruby-rails_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: test-ruby-rails_production
  username: <%= ENV['TEST-RUBY-RAILS_DATABASE_USERNAME'] %>
  password: <%= ENV['TEST-RUBY-RAILS_DATABASE_PASSWORD'] %>
